version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: ragflow-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: always

  redis:
    image: redis:7
    container_name: ragflow-redis
    ports:
      - "6379:6379"
    restart: always

  api:
    build: ../api
    container_name: ragflow-api
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - qdrant
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ../api/app:/app/app
    restart: on-failure

volumes:
  qdrant_data:
